# Configuration
title: Frank Taillandier
description: Articles & traductions
url: https://frank.taillandier.me
repository: DirtyF/frank.taillandier.me
branch: master
github:
  source:
    branch: master
baseurl: ""
permalink: pretty

sass:
  style: compressed

# Liquid
strict_front_matter: true
liquid:
  error_mode: strict

jekyll_tidy:
  compress_html: true
  ignore_env: development

# seo-tag
logo: /assets/img/frank-taillandier.jpg
twitter:
  username: DirtyF
social:
  name: Frank Taillandier
  links:
    - http://lanyrd.com/profile/dirtyf/
    - http://www.last.fm/user/DirtyF
    - https://github.com/DirtyF
    - https://keybase.io/dirtyf
    - https://twitter.com/DirtyF

cloudinary:
  cloud_name: jamstatic
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 720
      fallback_max_width: 720
      steps: 3
      sizes: "(min-width: 56em) calc(56em - 2rem), 100vw"

# reading_time
reading_time:
  words_per_minute: 180
  translations:
    about: environ
    minute: minute
    minutes: minutes

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      author: "Frank Taillandier"

include:
  - _headers
  - _pages

lsi: true

pagination:
  enabled: false
  per_page: 20
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

jekyll_compose:
  auto_open: true

exclude:
  - .editorconfig
  - .stylelintrc.json
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - script
  - tmp
  - vendor

plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-last-modified-at
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-tidy
  - jemoji
  # jekyll-paginate-v2

# About
author:
  name: Frank Taillandier
  email: frank@taillandier.me
  twitter: DirtyF

# External apps
analytics:
  google:
    tracking_id: UA-15560088-1
    site_verification: KhnXRq1e9zCBkD6X4vs_xwVc-6c-5an2vE7f0_-XMiE

disqus:
  shortname: franktaillandier

pwa:
  sw_filename: service-worker.js
  dest_js_directory: assets/js
  cache_name: franktaillandier # Optional
  precache_channel_name: sw-precache # Optional
  precache_recent_posts_num: 10 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "assets/{js,css,favicons,img,fonts}/**/*.{js,css,woff2,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
