# Setup
title:               Frank Taillandier
description:         Consultant web agile & UX
github:
  url: http://frank.taillandier.me
repository: DirtyF/frank.taillandier.me

baseurl:             ""
permalink:           pretty
excerpt_separator:   <!-- excerpt -->
paginate:            10

# About/contact
author:
  name: Frank Taillandier
  email: frank.taillandier@gmail.com
  twitter: DirtyF

analytics:
  google:
    tracking_id: UA-15560088-1
    site_verification: KhnXRq1e9zCBkD6X4vs_xwVc-6c-5an2vE7f0_-XMiE

# SEO
logo: /assets/img/frank-taillandier.jpg
twitter:
  username: DirtyF
social:
  type: person
  links:
    - https://github.com/DirtyF
    - http://lanyrd.com/profile/dirtyf/
    - http://www.last.fm/user/DirtyF

kramdown:
  input: GFM

branch: gh-pages

sass:
  style: compressed

include:
  - "_pages"

exclude:
  - vendor
  - script
  - Gemfile
  - Gemfile.lock
  - Procfile
  - README.md
  - CNAME

gems:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from
